import streamlit as st

AZUREOPENAI_ENDPOINT = st.secrets["AZUREOPENAI_ENDPOINT"]
AZUREOPENAI_API_KEY = st.secrets["AZUREOPENAI_API_KEY"]
AZUREOPENAI_API_VERION = "2024-02-01"
AZUREOPENAI_MODEL = "gpt-4o"

EMBEDDING_MODEL = 'text-embedding-ada-002'